export const demoUser = {
    id: 1,
    name: 'Budi Santoso',
    nip: '199001012010011001',
    email: 'budi@kominfo.go.id',
    rank: 'Penata Muda Tk. I (III/b)',
    position: 'Analis Sistem Informasi',
    phone: '08123456789',
    signature_path: null,
    is_active: true,
    roles: ['Admin Inisiasi'],
    permissions: [
        'change.initiation.view', 'change.initiation.create', 'change.initiation.submit',
        'change.initiation.approve', 'change.initiation.reject',
        'change.implementation.create', 'change.implementation.view',
        'change.implementation.update', 'change.implementation.submit',
        'change.implementation.review',
        'wfh.attendance.create', 'wfh.report.create',
        'wfh.report.update', 'wfh.report.delete', 'wfh.report.approve',
        'wfh.report.reject', 'wfh.report.export_pdf',
        'user.manage', 'role.manage', 'permission.manage',
    ],
    team: {
        id: 1,
        name: 'Tim Aplikasi',
        leader: { id: 2, name: 'Drs. Ahmad Fauzi' },
        field: { id: 1, name: 'Bidang Aplikasi Informatika' },
    },
};

export const demoInitiations = [
    {
        id: 1,
        doc_number: '001/INS/VII/2024',
        field_id: 1,
        initiator_id: 1,
        reviewer_id: null,
        initiation_date: '2024-07-12',
        needed_by_date: '2024-12-31',
        description: 'Pengembangan Modul Laporan Real-time Monitoring WFH',
        reason: 'Diperlukan sistem monitoring WFH yang terintegrasi untuk memudahkan pengawasan dan pelaporan kegiatan kerja dari rumah.',
        status: 'approved',
        review_status: 'approved',
        reviewed_at: null,
        review_reason: null,
        initiator_signed_at: '2024-07-12T08:00:00',
        verification_token: 'abc123def456',
        field: { id: 1, name: 'Bidang Aplikasi Informatika' },
        initiator: { id: 1, name: 'Budi Santoso', nip: '199001012010011001' },
        reviewer: null,
        implementations: [
            { id: 1, priority: 'Tinggi', impact: 'Sedang', status: 'submitted' },
        ],
    },
    {
        id: 2,
        doc_number: '002/INS/VII/2024',
        field_id: 1,
        initiator_id: 2,
        reviewer_id: null,
        initiation_date: '2024-07-11',
        needed_by_date: '2024-11-30',
        description: 'Integrasi API SIAK untuk Sinkronisasi Data Kepegawaian',
        reason: 'Data kepegawaian perlu disinkronkan secara otomatis antara sistem yang ada dengan SIAK untuk menghindari duplikasi data.',
        status: 'pending',
        review_status: null,
        reviewed_at: null,
        review_reason: null,
        initiator_signed_at: '2024-07-11T09:00:00',
        verification_token: null,
        field: { id: 1, name: 'Bidang Aplikasi Informatika' },
        initiator: { id: 2, name: 'Sari Dewi', nip: '199002022010012002' },
        reviewer: null,
        implementations: [],
    },
    {
        id: 3,
        doc_number: '003/INS/VII/2024',
        field_id: 2,
        initiator_id: 3,
        reviewer_id: 1,
        initiation_date: '2024-07-10',
        needed_by_date: '2024-10-15',
        description: 'Migrasi Server Database ke Infrastruktur Cloud',
        reason: 'Server database saat ini sudah mencapai kapasitas maksimal dan perlu dimigrasi ke cloud untuk skalabilitas.',
        status: 'rejected',
        review_status: 'rejected',
        reviewed_at: '2024-07-14T10:00:00',
        review_reason: 'Biaya migrasi belum dianggarkan di tahun ini. Ajukan ulang di periode anggaran berikutnya.',
        initiator_signed_at: '2024-07-10T08:30:00',
        verification_token: null,
        field: { id: 2, name: 'Bidang Infrastruktur Teknologi' },
        initiator: { id: 3, name: 'Budi Prasetyo', nip: '199003032010013003' },
        reviewer: { id: 1, name: 'Budi Santoso', nip: '199001012010011001' },
        implementations: [],
    },
    {
        id: 4,
        doc_number: '004/INS/VII/2024',
        field_id: 3,
        initiator_id: 4,
        reviewer_id: null,
        initiation_date: '2024-07-09',
        needed_by_date: '2024-09-30',
        description: 'UI/UX Redesign Dashboard Aplikasi Pelayanan Publik',
        reason: 'Dashboard saat ini memiliki tampilan yang kurang user-friendly dan perlu redesain untuk meningkatkan pengalaman pengguna.',
        status: 'draft',
        review_status: null,
        reviewed_at: null,
        review_reason: null,
        initiator_signed_at: null,
        verification_token: null,
        field: { id: 3, name: 'Bidang Layanan Digital' },
        initiator: { id: 4, name: 'Dina Amelia', nip: '199004042010014004' },
        reviewer: null,
        implementations: [],
    },
    {
        id: 5,
        doc_number: '005/INS/VII/2024',
        field_id: 4,
        initiator_id: 5,
        reviewer_id: 1,
        initiation_date: '2024-07-08',
        needed_by_date: '2024-12-20',
        description: 'Implementasi Single Sign-On (SSO) untuk Semua Aplikasi Internal',
        reason: 'Pengguna harus login berulang kali ke aplikasi yang berbeda. SSO akan meningkatkan produktivitas dan keamanan.',
        status: 'approved',
        review_status: 'approved',
        reviewed_at: '2024-07-15T11:00:00',
        review_reason: null,
        initiator_signed_at: '2024-07-08T10:00:00',
        verification_token: 'xyz789abc012',
        field: { id: 4, name: 'Bidang Keamanan Informasi' },
        initiator: { id: 5, name: 'Eko Prasetyo', nip: '199005052010015005' },
        reviewer: { id: 1, name: 'Budi Santoso', nip: '199001012010011001' },
        implementations: [],
    },
];
