<?php

namespace Tests\Feature;

use App\Domains\ChangeManagement\Models\ChangeInitiation;
use App\Models\Field;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class QrVerificationTest extends TestCase
{
    use RefreshDatabase;

    private User $initiator;
    private Field $field;

    protected function setUp(): void
    {
        parent::setUp();
        $this->artisan('db:seed', ['--class' => 'RolePermissionSeeder']);
        $this->initiator = User::factory()->create();
        $this->field = Field::factory()->create();
    }

    public function test_verify_endpoint_returns_404_for_invalid_hash(): void
    {
        $response = $this->getJson('/api/verify/invalidhash123');

        $response->assertStatus(404);
    }

    public function test_verify_endpoint_returns_document_info_for_valid_wfh_hash(): void
    {
        // Hash generated by QrCodeService::generateVerificationUrl
        $docNumber = 'WFH-1';
        $content = 'test-content';
        $hash = hash('sha256', $docNumber . '|' . $content);

        $response = $this->getJson("/api/verify/{$hash}");

        // This should return 200 with document info
        $response->assertStatus(200)
            ->assertJsonStructure([
                'success',
                'data' => ['hash', 'status'],
            ]);
    }

    public function test_verify_endpoint_returns_document_info_for_valid_change_hash(): void
    {
        $initiation = ChangeInitiation::factory()->create([
            'field_id' => $this->field->id,
            'initiator_id' => $this->initiator->id,
        ]);

        $hash = hash('sha256', $initiation->doc_number . '|' . $initiation->description);

        $response = $this->getJson("/api/verify/{$hash}");

        $response->assertStatus(200)
            ->assertJsonPath('success', true);
    }

    public function test_verify_hash_has_correct_length(): void
    {
        $hash = hash('sha256', 'test-data');

        $this->assertEquals(64, strlen($hash));
        $this->assertMatchesRegularExpression('/^[a-f0-9]{64}$/', $hash);
    }
}
